# Use with lora_finetune_distributed.py

# These are set by the job launcher, don't set them manually
base_model_path:
output_dir:
shuffle:
batch_size:
epochs:


# Tokenizer
tokenizer:
  _component_: torchtune.models.mistral.mistral_tokenizer
  path: ${base_model_path}/tokenizer.model

# Dataset
dataset:
  _component_:  # leave empty, this is injected by the job launcher
seed: null

# Model Arguments
model:
  _component_: torchtunewrapper.models.lora_mistral_8x7b
  lora_attn_modules: ['q_proj', 'k_proj', 'v_proj', "o_proj", "gate_proj", "up_proj", "down_proj", "lm_head"]
  apply_lora_to_mlp: True
  apply_lora_to_output: True
  lora_rank: 64
  lora_alpha: 16

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: ${base_model_path}
  checkpoint_files: [
    model-00001-of-00019.safetensors,
    model-00002-of-00019.safetensors,
    model-00003-of-00019.safetensors,
    model-00004-of-00019.safetensors,
    model-00005-of-00019.safetensors,
    model-00006-of-00019.safetensors,
    model-00007-of-00019.safetensors,
    model-00008-of-00019.safetensors,
    model-00009-of-00019.safetensors,
    model-00010-of-00019.safetensors,
    model-00011-of-00019.safetensors,
    model-00012-of-00019.safetensors,
    model-00013-of-00019.safetensors,
    model-00014-of-00019.safetensors,
    model-00015-of-00019.safetensors,
    model-00016-of-00019.safetensors,
    model-00017-of-00019.safetensors,
    model-00018-of-00019.safetensors,
    model-00019-of-00019.safetensors,
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: MISTRAL
resume_from_checkpoint: False

optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
  weight_decay: 0.01
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torch.nn.CrossEntropyLoss
gradient_accumulation_steps: 1

# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True

# Reduced precision
dtype: bf16