log_level: DEBUG

# GCP SA key location
# Temporarily disabled because the local development service account is out of date with required permissions
# GOOGLE_APPLICATION_CREDENTIALS: .secrets/gcp_key.json