# Config for single device full fine-tuning in full_finetune_single_device.py

# These are set by the job launcher, don't set them manually
base_model_path:
output_dir:
shuffle:
batch_size:
epochs:
lr:
seed:

tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ${base_model_path}/original/tokenizer.model
  max_seq_len: null

dataset:
  _component_:  # leave empty, this is injected by the job launcher
  packed: False

model:
  _component_: torchtune.models.llama3_2.llama3_2_1b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${base_model_path}
  checkpoint_files: [
    model.safetensors
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3_2
resume_from_checkpoint: False

optimizer:
  _component_: bitsandbytes.optim.PagedAdamW8bit # Quantized - Memory efficient
  # _component_: torch.optim.Adam
  lr: ${lr}  # 2e-5

# Learning rate scheduler
lr_scheduler:
  _component_: torchtune.training.get_cosine_schedule_with_warmup
  num_warmup_steps: 5

loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
  num_output_chunks: 16  # (default: 8) To reduce memory ulitisation during loss computation as bf16 needs to be upcast to fp32
  ignore_index: -100  # (default: -100) To ignore tokens with this value during loss computation. 

max_steps_per_epoch: null
gradient_accumulation_steps: 1

device: cuda

# Memory management
dtype: bf16
enable_activation_checkpointing: False
enable_activation_offloading: False
optimizer_in_bwd: True
compile: False

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}/tt_logs
log_every_n_steps: 10
log_peak_memory_stats: True

profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False

  # Output directory of trace artifacts
  output_dir: ${output_dir}/tt_profiling_outputs

  # `torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  # trace options passed to `torch.profiler.profile`
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1