job_id: null
category: null
type: null

dataset_id: null
dataset_kind: single_label
dataset_provider: huggingface
dataset_fetch_config:
  name: null

train_split: train
test_split: test

single_label_dataset_config:
  input_col: null
  label_col: null
  master_column: null

preprocessor: null
<preprocessor name>_dataset_config:
  transforms_input_func: null
  transforms_label_func: null

tokenizer_id: null

model_base: null
model_base_args: {}

loss_func_args: {}
loss_func_name: CrossEntropyLoss

batch_size: 8
learning_rate: 0.001
num_epochs: 10
shuffle: true
num_batches: null
