name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Update pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install python dependencies for `shared-lib`
        run: python -m pip install -r shared-lib/requirements.txt
      - name: Install unit test specific python dependencies for `shared-lib`
        run: python -m pip install -r shared-lib/requirements-test.txt
      - name: Run unit tests
        run: PYTHONPATH=./shared-lib/src:./ pytest -vv