name: Release

on:
  # Run workflow only if the unit tests workflow succeeds
  workflow_run:
    workflows: [ "Unit Tests" ]
    types: [ completed ]
    # Run workflow only in master branch
    branches: [ master ]
    # Run workflow only if these folders changed
    paths: ['lib-celery/**', 'lib-common/**', 'lib-workflows/**', 'app-configs/**', 'job-configs/**', 'celery.Dockerfile', 'scripts/**']

# Allows this workflow to push changes to the git repo
# we need this to commit and push the updated VERSION file
permissions:
  contents: write

env:
  IMAGE_NAME: train_evaluate-workflow
  IMAGE_TAG: us-central1-docker.pkg.dev/neat-airport-407301/lum-docker-images/train_evaluate-workflow
  WORKFLOW_URL: "${{github.SERVER_URL}}/${{github.REPOSITORY}}/actions/runs/${{github.RUN_ID}}"
  ARTIFACT_REPO_URL: "https://console.cloud.google.com/artifacts/docker/neat-airport-407301/us-central1/lum-docker-images/train_evaluate-workflow?project=neat-airport-407301"

jobs:
  release:
    runs-on: ubuntu-latest
    # Run workflow only if the unit tests workflow succeeds
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4
      - name: Set COMMIT_AUTHOR env
        run: echo "COMMIT_AUTHOR=$(git log -1 --pretty=%an)" >> $GITHUB_ENV
      # To capture the author, the following step needs to run after git checkout
      - name: Notify Slack - Started
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"version: `pending` | commit: `${{github.SHA}}` | user: `${{env.COMMIT_AUTHOR}}` | status: `started` | <${{env.WORKFLOW_URL}}|GHA link>"}' \
          https://hooks.slack.com/services/${{secrets.SLACK_KEY_RELEASES}}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up Google Cloud SDK Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          token_format: 'access_token'
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - name: "Use gcloud CLI"
        run: "gcloud info"
      - name: "Docker auth"
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: Bump Version
        run: PYTHONPATH=$(pwd)/lib-common/src python ./scripts/bump_version.py -p minor
      - name: Build Docker Image
        run: |
          VERSION=$(cat VERSION)
          docker build -f celery.Dockerfile -t $IMAGE_NAME:$VERSION .
      - name: Build image
        run: docker build . -f celery.Dockerfile -t $IMAGE_NAME
      - name: Tag image with version tag and artifact registry URL
        run: docker tag $IMAGE_NAME $IMAGE_TAG:$(cat VERSION)
      - name: Tag image `latest` tag and artifact registry URL
        run: docker tag $IMAGE_NAME $IMAGE_TAG:latest
      - name: Push image (version tag)
        run: docker push $IMAGE_TAG:$(cat VERSION)
      - name: Push image (latest tag)
        run: docker push $IMAGE_TAG:latest
      - name: Commit new version and push to git repo
        run: |
          git config --global user.name 'lumino-bot'
          git config --global user.email 'lumino-bot@luminolabs.ai'
          git commit -am "Version bump to $(cat VERSION)"
          git push
      - name: Notify Slack - Success
        run: |
          VERSION=$(cat VERSION)
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"version: `'"$VERSION"'` | commit: `${{github.SHA}}` | user: `${{env.COMMIT_AUTHOR}}` | status: `success` | <${{env.WORKFLOW_URL}}|GHA link> | <${{env.ARTIFACT_REPO_URL}}|image link>"}' \
          https://hooks.slack.com/services/${{secrets.SLACK_KEY_RELEASES}}
  on-failure:
    if: failure() || cancelled()
    needs: [ release ]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack - Failure
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"version: `none` | commit: `${{github.SHA}}` | user: `${{env.COMMIT_AUTHOR}}` | status: `failed` | <${{env.WORKFLOW_URL}}|GHA link>"}' \
          https://hooks.slack.com/services/${{secrets.SLACK_KEY_RELEASES}}