name: Unit Tests

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Update pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install python dependencies for `lib-common`
        run: python -m pip install -r lib-common/requirements.txt
      - name: Install unit test specific python dependencies for `lib-common`
        run: python -m pip install -r lib-common/requirements-test.txt
      - name: Run unit tests
        run: PYTHONPATH=./lib-common/src:./ pytest -vv